### ISSUE TITLE
关于数据的获取

### ISSUE THREAD

**Issue by supercoderhawk** [WILAB-HIT/Resources#1]
请问你们在论文里提到的标注的数百份病历数据能够进行共享吗？我们的课题对这些数据有很强烈的需求。

还有去年曾今发邮件询问过关毅教授，他说好像有发布到LDC，但是好像还没见到。。

如果需要什么申请和证明的话我们都可以提供，以**上海理工大学医学信息工程研究所**的名义。

**Comment by ghost** [comment]
@xyb930826 您好，我们目前的数据还在完善并且扩充规模，会在不久后对学术界公开，目前还不便共享。本库中有标注规范、标注工具及一些标注样例，如有研究需求可以详细了解一下。

**Comment by marcwww** [comment]
请问数据现在可以获取了吗

**Comment by middream** [comment]
请问数据集现在公开了吗？
