### ISSUE TITLE
你好，为什么关系导出的出现错误

### ISSUE THREAD

**Issue by lyfree132** [WILAB-HIT/Resources#2]
在使用标注工具标注关系时，标注实体关系实体类型为null,而且导出的格式也和样本中给出的不同，请问是什么原因？
正侧位片【261-265】null||R=Te2D:TeRD||类风湿关节炎【275-281】null
胆囊结石【715-719】null||R=Tr2D:TrAD||胆囊切除术【726-731】null
胆囊炎【720-723】null||R=Tr2D:TrAD||胆囊切除术【726-731】null

**Comment by BinHeRunning** [comment]
需要先进行实体标注,然后再进行关系标注

**Comment by BinHeRunning** [comment]
@lyfree132 需要先进行实体标注,然后再进行关系标注
