### ISSUE TITLE
Hi, how to open the demo website

### ISSUE THREAD

**Issue by jluo41** [WILAB-HIT/Resources#3]
I really appreciate your team's impressing work. 

Recently, I find I can't open your demo website: http://wi.hit.edu.cn/cemr/

Not only me, my classmates cannot open it, either. I remember that I could open that website in June. I wonder what happened to that website? 

Could you make it accessible again please?

Thanks 

👍

**Comment by BinHeRunning** [comment]
@floydluo Hi, thank you for your attention to our research. Recently,  there are some problems with the network in some colleges. And the demo is ok and will be accessible soon.
