### ISSUE TITLE
关于annotation tool的论文

### ISSUE THREAD

**Issue by My-captain** [WILAB-HIT/Resources#4]
您好，请问是否有谈及annotation tool或者《基于中文电子病历文本的在线演示》算法实现的论文？
如果有，可否提供一下，感激不尽。

**Comment by BinHeRunning** [comment]
> 您好，请问是否有谈及annotation tool或者《基于中文电子病历文本的在线演示》算法实现的论文？
> 如果有，可否提供一下，感激不尽。

不好意思，没有相关文章，标注工具源码可以参照https://github.com/yangjinfeng/emrproject
